export default [
  {
    _id: '1',
    title: 'Wireless Communication',
    category: 'COMM',
    createdAt: '2025-04-20',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    thumbnail: 'https://placehold.co/600x800',
    viewCount: 0,
  },
  {
    _id: '2',
    title: 'Distributed System',
    category: 'SOFT',
    createdAt: '2024-09-29',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    thumbnail: 'https://placehold.co/600x800',
    viewCount: 0,
  },
  {
    _id: '3',
    title: 'Resource Management Principles',
    category: 'SOFT',
    createdAt: '2024-05-10',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    thumbnail: 'https://placehold.co/600x800',
    viewCount: 0,
  },
  {
    _id: '4',
    title: '4G Notes',
    category: 'COMM',
    createdAt: '2025-01-29',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    thumbnail: 'https://placehold.co/600x800',
    viewCount: 0,
  },
  {
    _id: '5',
    title: 'Cellular Communication ECE',
    category: 'COMM',
    createdAt: '2025-04-10',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    thumbnail: 'https://placehold.co/600x800',
    viewCount: 0,
  },
];
