services:

  admin-dashboard:
    image: vayureader-admin-dashboard:latest
    container_name: vayureader_admin
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - backend-network

  mongo:
    image: mongo:6-jammy
    container_name: vayureader_db
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network

  redis:
    image: redis:7.2-alpine
    container_name: vayureader_cache
    restart: unless-stopped
    networks:
      - backend-network

  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: vayureader_search
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - backend-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vayureader-app:latest
    container_name: vayureader_api
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./uploads:/usr/src/app/uploads
    depends_on:
      - mongo
      - redis
      - elasticsearch
    networks:
      - backend-network

  nginx:
    image: nginx:1.25-alpine
    container_name: vayureader_gateway
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./uploads:/usr/src/app/uploads:ro
    depends_on:
      - app
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  mongo-data:
  es-data:
